/*
 * Bubbles for Master System
 * A Bust-A-Move clone for the Sega Master System
 *
 * Bank 2 - In-game VDP Pattern data.
 *
 * NOTE: For now, this is manually created with sizes populated for sizeof () support.
 *       Moving forward, this header should become auto-generated by Sneptile.
 */

extern const uint32_t border_patterns [64];
extern const uint32_t bubbles_grey_patterns [1272];
extern const uint32_t grass_patterns [48];
extern const uint32_t next_patterns [24];
extern const uint32_t pip_patterns [8];
extern const uint32_t text_patterns [528];
