/*
 * Bubbles for Master System
 * A Bust-A-Move clone for the Sega Master System
 *
 * Bank 3 - In-game VDP Pattern data.
 *
 * NOTE: For now, this is manually created with sizes populated for sizeof () support.
 *       Moving forward, this header should become auto-generated by Sneptile.
 */

extern const uint32_t bubbles_patterns [3176];
